### ISSUE TITLE
joint_state_publisher

### ISSUE THREAD

**Issue by robolug** [abdulkadrtr/multiRobotExploration-RobotArmy#1]
Caught exception in launch (see debug for traceback): "package 'joint_state_publisher' not found, searching:
This error is appearing when  I launch world, but I cant see any package by this name in launch file 
`
ros2 launch turtlebot3_gazebo multi_robot_launch.py
`

**Comment by abdulkadrtr** [comment]
Hi, 
the joint state publisher is a ROS2 package. To install it, run the command:
 `sudo apt install ros-humble-joint_state_publisher`
